service: launchdarkly-dynamo-example

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'staging'}
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/launchdarkly-${self:provider.stage}
  environment:
    LAUNCHDARKLY_DYNAMODB_TABLE: launchdarkly-${self:provider.stage}
    LAUNCHDARKLY_SDK_KEY: ${ssm:/launchdarkly/${self:provider.stage}/sdkkey~true}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  flags:
    handler: bin/flags
    events:
      - http:
         path: /
         method: get
