service: serverless-ldr

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'staging'}
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource:
        - Fn::GetAtt:
            - FeaturesTable
            - Arn
        - Fn::GetAtt:
            - SegmentsTable
            - Arn
  environment:
    DYNAMODB_TABLE_PREFIX: launchdarkly-${self:provider.stage}-
    LAUNCHDARKLY_SDK_KEY: ${ssm:/launchdarkly/${self:provider.stage}/sdkkey~true}
    LAUNCHDARKLY_WEBHOOK_SECRET: ${ssm:/launchdarkly/${self:provider.stage}/webhooksecret~true}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  store:
    handler: bin/store
    events:
      - http:
         path: /
         method: post

resources:
  Resources:
    FeaturesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: launchdarkly-${self:provider.stage}-features
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    SegmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: launchdarkly-${self:provider.stage}-segments
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
