service: serverless-ldr

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'staging'}
  region: ${env:AWS_REGION}
  environment:
    LAUNCHDARKLY_SDK_KEY: ${env:LAUNCHDARKLY_SDK_KEY}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  flags:
    handler: bin/flags
    events:
      - http:
         path: /flags
         method: post
