service: serverless-ldr

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'staging'}
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource:
        - Fn::GetAtt:
            - DynamoDBTable
            - Arn
  environment:
    LAUNCHDARKLY_DYNAMODB_TABLE: launchdarkly-${self:provider.stage}
    LAUNCHDARKLY_SDK_KEY: ${ssm:/launchdarkly/${self:provider.stage}/sdkkey~true}
    LAUNCHDARKLY_WEBHOOK_SECRET: ${ssm:/launchdarkly/${self:provider.stage}/webhooksecret~true}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  store:
    handler: bin/store
    events:
      - http:
         path: /
         method: post

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: launchdarkly-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
          - AttributeName: namespace
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
          - AttributeName: namespace
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
